---
title: "Readings"
description: "Current Readings"
---

# Articles
      
 <ol class="references">
  <li class="reference">
    <div class="title">Ten Things You Should Know about Transposable Elements</div>
    <div class="authors">Guillaume Bourque, et al.</div>
    <div class="details">Genome Biology, vol. 19, no. 1, Nov. 2018, p. 199.</div>
    <div class="links"><a href="https://doi.org/10.1186/s13059-018-1577-z">https://doi.org/10.1186/s13059-018-1577-z</a></div>
  </li>
  <li class="reference">
    <div class="title">History of the Discovery of a Master Locus Producing PiRNAs: The Flamenco/COM Locus in Drosophila Melanogaster</div>
    <div class="authors">Goriaux Coline, et al.</div>
    <div class="details">Frontiers in Genetics, vol. 5, Aug. 2014, p. 257.</div>
    <div class="links"><a href="https://doi.org/10.3389/fgene.2014.00257">https://doi.org/10.3389/fgene.2014.00257</a></div>
  </li>
  <li class="reference">
    <div class="title">De Novo Assembly and Annotation of the Asian Tiger Mosquito (Aedes Albopictus) Repeatome with DnaPipeTE from Raw Genomic Reads and Comparative Analysis with the Yellow Fever Mosquito (Aedes Aegypti)</div>
    <div class="authors">Clément Goubert, et al.</div>
    <div class="details">Genome Biology and Evolution, vol. 7, no. 4, Apr. 2015, pp. 1192–205.</div>
    <div class="links"><a href="https://doi.org/10.1093/gbe/evv050">https://doi.org/10.1093/gbe/evv050</a></div>
  </li>
  <li class="reference">
    <div class="title">Transposable Element Dynamics Are Consistent across the Drosophila Phylogeny, despite Drastically Differing Content</div>
    <div class="authors">Tom Hill</div>
    <div class="details">preprint, Genomics, 27 May 2019.</div>
    <div class="links"><a href="https://doi.org/10.1101/651059">https://doi.org/10.1101/651059</a></div>
  </li>
  <li class="reference">
    <div class="title">Specialized PiRNA Pathways Act in Germline and Somatic Tissues of the Drosophila Ovary</div>
    <div class="authors">Colin D. Malone, et al.</div>
    <div class="details">Cell, vol. 137, no. 3, May 2009, pp. 522–35.</div>
    <div class="links"><a href="https://doi.org/10.1016/j.cell.2009.03.040">https://doi.org/10.1016/j.cell.2009.03.040</a></div>
  </li>
  <li class="reference">
	<div class="title">PIWI-Interacting RNAs: Small RNAs with Big Functions</div>
	    <div class="authors">Deniz M. Ozata, et al.</div>
	    <div class="details">Nature Reviews. Genetics, vol. 20, no. 2, Feb. 2019, pp. 89–108.</div>
	    <div class="links"><a href="https://doi.org/10.1038/s41576-018-0073-3">https://doi.org/10.1038/s41576-018-0073-3</a></div>
  </li>
  <li class="reference">
    <div class="title">Transposable Elements in Drosophila</div>
    <div class="authors">Vincent Mérel, et al.</div>
    <div class="details">Mobile DNA, vol. 11, no. 1, July 2020, p. 23.</div>
    <div class="links"><a href="https://doi.org/10.1186/s13100-020-00213-z">https://doi.org/10.1186/s13100-020-00213-z</a></div>
  </li>
  <li class="reference">
    <div class="title">Distribution, Evolution, and Diversity of Retrotransposons at the Flamenco Locus Reflect the Regulatory Properties of PiRNA Clusters</div>
    <div class="authors">Vanessa Zanni, et al.</div>
    <div class="details">Proceedings of the National Academy of Sciences of the United States of America, vol. 110, no. 49, Dec. 2013, pp. 19842–47.</div>
    <div class="links"><a href="https://doi.org/10.1073/pnas.1313677110">https://doi.org/10.1073/pnas.1313677110</a></div>
  </li>
</ol>

# Books

## Information Theory and Physics
- [ ] "The Information: A History, A Theory, A Flood" by James Gleick
- [ ] "Quantum Computation and Quantum Information" by Michael A. Nielsen and Isaac L. Chuang

## Consciousness and Information Theory
- [ ] "Consciousness and the Brain: Deciphering How the Brain Codes Our Thoughts" by Stanislas Dehaene
- [ ] "The Feeling of Life Itself: Why Consciousness Is Everywhere But Can't Be Computed" by Christof Koch

## Evolutionary Biology and Behavior
- [ ] "The Selfish Gene" by Richard Dawkins
- [ ] "The Red Queen: Sex and the Evolution of Human Nature" by Matt Ridley

## Philosophy and Existentialism
- [ ] "Being and Nothingness" by Jean-Paul Sartre
- [ ] "The Myth of Sisyphus" by Albert Camus


