direction: right

Stable Marriage Problem: {
  Men: {
    man1: Man 1
    man2: Man 2
    man3: Man 3
    man4: Man 4
  }

  Women: {
    woman1: Woman 1
    woman2: Woman 2
    woman3: Woman 3
    woman4: Woman 4
  }

  men.man1 -> women.woman1: Proposal 1 {
    style.animated: true
  }
  men.man1 -> women.woman2: Proposal 2 {
    style.animated: true
  }
  men.man2 -> women.woman3: Proposal 3 {
    style.animated: true
  }
  men.man2 -> women.woman4: Proposal 4 {
    style.animated: true
  }
  men.man3 -> women.woman1: Proposal 5 {
    style.animated: true
  }
  men.man3 -> women.woman2: Proposal 6 {
    style.animated: true
  }
  men.man4 -> women.woman3: Proposal 7 {
    style.animated: true
  }
  men.man4 -> women.woman4: Proposal 8 {
    style.animated: true
  }

  (men.man1 -> women.woman1)[0].style.stroke: orange
  (men.man2 -> women.woman3)[0].style.stroke: black
  (men.man3 -> women.woman2)[0].style.stroke: green
  (men.man4 -> women.woman4)[0].style.stroke: purple
}
