direction: down

classes: {
  person: {
    shape: person
    width: 150
  }

  smartphone: {
    shape: hexagon
    width: 60
  }

  computer: {
    shape: monitor
    width: 100
  }

  thought: {
    shape: cloud
  }
}

You.class: person

Bored.class: thought
Craving.class: thought

You -> Bored: Feel bored {
    style.animated: true
  }
You -> Craving: Crave stimulation{
    style.animated: true
  }

Bored -> Craving: Get temporary stimulation{
    style.animated: true
  }
Craving -> You: Seek more distractions{
    style.animated: true
  }
