direction: right
SIR Model: {
  shape: sequence_diagram
  susceptible: Susceptible (S)
  infected: Infected (I)
  recovered: Recovered (R)
  vaccinated: Vaccinated
  death: Death

  stages: {
    susceptible -> infected: Exposed to infection.
    infected -> infected: Infect others.
    infected -> recovered: Recovered from disease.
    infected -> vaccinated: Get Vaccinated.
    infected -> death: Death due to disease.
  }
}
