direction: right
SIR Model: {
  shape: sequence_diagram
  susceptible: Susceptible (S)
  infected: Infected (I)
  recovered: Recovered (R)
  vaccinated: Vaccinated
  death: Death

  stages: {
    susceptible -> infected: Exposed to infection. {
      style.animated: true
    }
    infected -> infected: Infect others. {
      style.animated: true
    }
    infected -> recovered: Recovered from disease. {
      style.animated: true
    }
    infected -> vaccinated: Get Vaccinated. {
      style.animated: true
    }
    infected -> death: Death due to disease. {
      style.animated: true
    }
  }
}
